import { useFonts } from "expo-font";

export function useExpoFonts() {
  const [fontsLoaded, fontError] = useFonts({
    BebasNeueRegular: require("../assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf"),

    FiraCodeBold: require("../assets/fonts/Fira_Code/FiraCode-Bold.ttf"),
    FiraCodeLight: require("../assets/fonts/Fira_Code/FiraCode-Light.ttf"),
    FiraCodeMedium: require("../assets/fonts/Fira_Code/FiraCode-Medium.ttf"),
    FiraCodeRegular: require("../assets/fonts/Fira_Code/FiraCode-Regular.ttf"),
    FiraCodeSemiBold: require("../assets/fonts/Fira_Code/FiraCode-SemiBold.ttf"),
    FiraCodeVariable: require("../assets/fonts/Fira_Code/FiraCode-VariableFont_wght.ttf"),

    MontserratVariable: require("../assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf"),
    MontserratItalicVariable: require("../assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf"),
    MontserratBlack: require("../assets/fonts/Montserrat/static/Montserrat-Black.ttf"),
    MontserratBlackItalic: require("../assets/fonts/Montserrat/static/Montserrat-BlackItalic.ttf"),
    MontserratBold: require("../assets/fonts/Montserrat/static/Montserrat-Bold.ttf"),
    MontserratBoldItalic: require("../assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf"),
    MontserratExtraBold: require("../assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf"),
    MontserratExtraBoldItalic: require("../assets/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf"),
    MontserratExtraLight: require("../assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf"),
    MontserratExtraLightItalic: require("../assets/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf"),
    MontserratItalic: require("../assets/fonts/Montserrat/static/Montserrat-Italic.ttf"),
    MontserratLight: require("../assets/fonts/Montserrat/static/Montserrat-Light.ttf"),
    MontserratLightItalic: require("../assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf"),
    MontserratMedium: require("../assets/fonts/Montserrat/static/Montserrat-Medium.ttf"),
    MontserratMediumItalic: require("../assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf"),
    MontserratRegular: require("../assets/fonts/Montserrat/static/Montserrat-Regular.ttf"),
    MontserratSemiBold: require("../assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf"),
    MontserratSemiBoldItalic: require("../assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf"),
    MontserratThin: require("../assets/fonts/Montserrat/static/Montserrat-Thin.ttf"),
    MontserratThinItalic: require("../assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf"),

    OpenSansVariable: require("../assets/fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf"),
    OpenSansItalicVariable: require("../assets/fonts/Open_Sans/OpenSans-Italic-VariableFont_wdth,wght.ttf"),
    OpenSansCondensedBold: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-Bold.ttf"),
    OpenSansCondensedBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-BoldItalic.ttf"),
    OpenSansCondensedExtraBold: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-ExtraBold.ttf"),
    OpenSansCondensedExtraBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-ExtraBoldItalic.ttf"),
    OpenSansCondensedItalic: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-Italic.ttf"),
    OpenSansCondensedLight: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-Light.ttf"),
    OpenSansCondensedLightItalic: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-LightItalic.ttf"),
    OpenSansCondensedMedium: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-Medium.ttf"),
    OpenSansCondensedMediumItalic: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-MediumItalic.ttf"),
    OpenSansCondensedRegular: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-Regular.ttf"),
    OpenSansCondensedSemiBold: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-SemiBold.ttf"),
    OpenSansCondensedSemiBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans_Condensed-SemiBoldItalic.ttf"),
    OpenSansSemiCondensedBold: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-Bold.ttf"),
    OpenSansSemiCondensedBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-BoldItalic.ttf"),
    OpenSansSemiCondensedExtraBold: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-ExtraBold.ttf"),
    OpenSansSemiCondensedExtraBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-ExtraBoldItalic.ttf"),
    OpenSansSemiCondensedItalic: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-Italic.ttf"),
    OpenSansSemiCondensedLight: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-Light.ttf"),
    OpenSansSemiCondensedLightItalic: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-LightItalic.ttf"),
    OpenSansSemiCondensedMedium: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-Medium.ttf"),
    OpenSansSemiCondensedMediumItalic: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-MediumItalic.ttf"),
    OpenSansSemiCondensedRegular: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-Regular.ttf"),
    OpenSansSemiCondensedSemiBold: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-SemiBold.ttf"),
    OpenSansSemiCondensedSemiBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans_SemiCondensed-SemiBoldItalic.ttf"),
    OpenSansBold: require("../assets/fonts/Open_Sans/static/OpenSans-Bold.ttf"),
    OpenSansBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans-BoldItalic.ttf"),
    OpenSansExtraBold: require("../assets/fonts/Open_Sans/static/OpenSans-ExtraBold.ttf"),
    OpenSansExtraBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans-ExtraBoldItalic.ttf"),
    OpenSansItalic: require("../assets/fonts/Open_Sans/static/OpenSans-Italic.ttf"),
    OpenSansLight: require("../assets/fonts/Open_Sans/static/OpenSans-Light.ttf"),
    OpenSansLightItalic: require("../assets/fonts/Open_Sans/static/OpenSans-LightItalic.ttf"),
    OpenSansMedium: require("../assets/fonts/Open_Sans/static/OpenSans-Medium.ttf"),
    OpenSansMediumItalic: require("../assets/fonts/Open_Sans/static/OpenSans-MediumItalic.ttf"),
    OpenSansRegular: require("../assets/fonts/Open_Sans/static/OpenSans-Regular.ttf"),
    OpenSansSemiBold: require("../assets/fonts/Open_Sans/static/OpenSans-SemiBold.ttf"),
    OpenSansSemiBoldItalic: require("../assets/fonts/Open_Sans/static/OpenSans-SemiBoldItalic.ttf"),

    PlayfairDisplayBlack: require("../assets/fonts/Playfair_Display/PlayfairDisplay-Black.ttf"),
    PlayfairDisplayBlackItalic: require("../assets/fonts/Playfair_Display/PlayfairDisplay-BlackItalic.ttf"),
    PlayfairDisplayBold: require("../assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf"),
    PlayfairDisplayBoldItalic: require("../assets/fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf"),
    PlayfairDisplayExtraBold: require("../assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf"),
    PlayfairDisplayExtraBoldItalic: require("../assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBoldItalic.ttf"),
    PlayfairDisplayItalic: require("../assets/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf"),
    PlayfairDisplayItalicVariable: require("../assets/fonts/Playfair_Display/PlayfairDisplay-Italic-VariableFont_wght.ttf"),
    PlayfairDisplayMedium: require("../assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf"),
    PlayfairDisplayMediumItalic: require("../assets/fonts/Playfair_Display/PlayfairDisplay-MediumItalic.ttf"),
    PlayfairDisplayRegular: require("../assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf"),
    PlayfairDisplaySemiBold: require("../assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf"),
    PlayfairDisplaySemiBoldItalic: require("../assets/fonts/Playfair_Display/PlayfairDisplay-SemiBoldItalic.ttf"),
    PlayfairDisplayVariable: require("../assets/fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf"),

    PoppinsBlack: require("../assets/fonts/Poppins/Poppins-Black.ttf"),
    PoppinsBlackItalic: require("../assets/fonts/Poppins/Poppins-BlackItalic.ttf"),
    PoppinsBold: require("../assets/fonts/Poppins/Poppins-Bold.ttf"),
    PoppinsBoldItalic: require("../assets/fonts/Poppins/Poppins-BoldItalic.ttf"),
    PoppinsExtraBold: require("../assets/fonts/Poppins/Poppins-ExtraBold.ttf"),
    PoppinsExtraBoldItalic: require("../assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf"),
    PoppinsExtraLight: require("../assets/fonts/Poppins/Poppins-ExtraLight.ttf"),
    PoppinsExtraLightItalic: require("../assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf"),
    PoppinsItalic: require("../assets/fonts/Poppins/Poppins-Italic.ttf"),
    PoppinsLight: require("../assets/fonts/Poppins/Poppins-Light.ttf"),
    PoppinsLightItalic: require("../assets/fonts/Poppins/Poppins-LightItalic.ttf"),
    PoppinsMedium: require("../assets/fonts/Poppins/Poppins-Medium.ttf"),
    PoppinsMediumItalic: require("../assets/fonts/Poppins/Poppins-MediumItalic.ttf"),
    PoppinsRegular: require("../assets/fonts/Poppins/Poppins-Regular.ttf"),
    PoppinsSemiBold: require("../assets/fonts/Poppins/Poppins-SemiBold.ttf"),
    PoppinsSemiBoldItalic: require("../assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf"),
    PoppinsThin: require("../assets/fonts/Poppins/Poppins-Thin.ttf"),
    PoppinsThinItalic: require("../assets/fonts/Poppins/Poppins-ThinItalic.ttf"),
  });

  return { fontsLoaded, fontError };
}

export default useExpoFonts;
